version: "3.8"

services:
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #     - 15692:15692
  
  healthcare.main:
    build: 
      context: ./
      dockerfile: main.Dockerfile
    image: healthcare_main
    container_name: healthcare_main
    ports:
      - 8000:8000
    volumes:
      - ./usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
